# Generated by Django 4.0.1 on 2022-02-09 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('IS', 'In stock'), ('OS', 'Out of stock')], default='IS', max_length=100),
        ),
    ]
